default: &default
  pool: 5
  timeout: 5000
  adapter: postgresql

development:
  <<: *default
  database: rj-travels

test:
  <<: *default
  database: rj-travels-test

production:
  <<: *default
  database: rj-travels
  pool: 5
  timeout: 5000
  username: roberto 
  password: gengar 
