# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Blog.create([
  {
    :title => 'One-way Ticket!',
    :name => 'one_way_ticket',
    :article => 'It’s official! I’m going to South America on the 30th of July! I will be flying into Cartagena and catching a bus to Santa Marta. There I will be staying with Paloma, a couchsurfing host who is gracious enough to host me! I plan on doing some scuba diving and checking out the national park Tayrona to the east.

        Joe and Natalie will also be flying into Bogota on the 14th of August so I have approximately 2 weeks to make my way there from the north coast of Colombia so I can meet up with them.

        Feeling very excited and also very anxious. I want to be on the plane already… Soon!',
    :date => DateTime.new(2017, 7, 20)
  }, 
  {
    :title => 'Going away...',
    :name => 'going_away',
    :article => 'Thank you to everyone who showed up to my going away party. Wish I could have stayed longer but… true to its name, I was going away! Thank you Neva and Jonnie for hosting, Berto for being the chef and the badass gifts, my mom for being the Coach, Ricardito for being the magician, the Schoengarths for making the party a lot more entertaining, Sarah for making it (even when you had to bus it), Kara and Collin for enriching the night with fantasy books discussions, Joe and Nat for driving me, and Jake for being forever creepy. Also everyone else who didn\'t make it but still wished me to have a good trip\: thank you.',
    :date => DateTime.new(2017, 7, 29)
  },
  {
    :title => 'Colombia!',
    :name => 'colombia',
    :article => 'Colombian Peso ~ 3,000 : $1

      The flight was uneventful. Drinking tequila and whiskey before made it so I fell asleep almost instantly on the plane… the 3 hour layover in Atlanta was terrible though. I should have slept on the floor and get some sleep but instead I was busy taking advantage of the free wifi and downloading songs and Netflix shows. Worth it, tunes are indispensable for waiting in the long immigration lines. By the way, they didn\'t even look at my masterfully falsified return ticket. I was afraid they were going to throw a fuzz if I didn\'t present documentation of a return flight but the guy was more concerned about what Couchsurfing was… Murphy\'s law (or maybe Sod’s law is more applicable) I suppose. Anyway, once I got through immigration I got bombarded with a lot of taxi offers.. right away I took a big inner sigh and reminded myself that this is what\'s it\'s like in third world countries, everyone trying to squeeze every peso out of you. I ended up taking a taxi to a bus terminal (15k COP) and the bus to Santa Marta with Berlitour ended up being about 40k COP (~$13). At the terminal I got a chicken empanada and a bottle of water for 3.5k COP ($1.5). The empanada was decent, fluffier than Venezuelan empanadas, the chicken filling was pretty great. On the way some guy got on the bus selling these junk snacks called rosquillas (2k COP for a package of 10ish), I almost got some out of curiosity and temptation but once I saw them up close I saw that they’re basically just some sort of waffle in a tiny donut shape. Empty calories, no thanks. Could have gotten some freshly squeezed OJ for 2k COP but no matter how cheap it is, no need for sugars. Hopefully I\'ll run into healthier options in Santa Marta. Second stop in Barranquilla, I caved in and got a ball of potatoes. Papa rellena they\'re called. Pretty delicious potato balls that are deep fried and stuffed with meat. Probably won\'t eat them again but boy are they delicious.

      Almost all day traveling. Finally made it to santa Marta around 8pm. Exhausted and groggy from the constant drifting in and out of sleep I missed my stop and started walking to the meeting spot. After about 10 min and diving deeper into the sketchy neighborhoods on my way downtown an old kind lady warned me not to go the way I was turning. My suspicions were correct. For about 5 min I was debating whether to get a taxi or just walk as punishment for missing my stop. I was being silly, why run the risk when a taxi can take me there in a matter of min for a few bucks. So I jumped on the next taxi I saw and met with Paloma at the square. We walked around a bunch and she was very kind, she led me to her home so I could drop off my backpack and we set out to walk around town. We stopped by one of her favorite places and I had a delicious ceviche arepa. Now we’re talking, I could live off this stuff. After a bit more walking we decided to call it a night and head back. Finally some much needed rest. Tomorrow I will be waking up early to do some scuba diving!
      (Santa Marta)',
    :date => DateTime.new(2017, 7, 30)
  },
  {
    :title => 'Santa Marta, Taganga and La Quinta de San Pedro Alejandrino Museum',
    :name => 'santa_marta_taganga_and_la_quinta_de_san_pedro_alejandrino_museum',
    :article => 'The day started off kind of slow. My alarm did little to get me out of bed and it kept raining outside making it even easier to stay in bed. 7 o’clock day start became a 9 o’clock one. Oh well, it felt great to sleep in. Finally got up and made my way to Taganga where I would meet up with the scuba shop I had been talking to before coming on this trip. Side note: the local busses are fun! Scary but fun. Sometimes the scale tips one way or the other but I like taking them. Who needs attraction parks, they won\'t be able to match the adrenaline some of these drivers give you… anyway, 1,600 COP and 30 min later I\'m there.
        (Buseta)
        Shirly, the girl at the front desk is very charming and I liked her right away… They do say it\'s not about the company you go through (padi, sdi, ssi, cmas, etc), it\'s about the instructors. Well I\'m sold! Joking aside, I grew more and more interested in the class the more she told me about it so I went for it. Starting tomorrow at 720 am I will be working on becoming an SDI advanced diver (600k COP). Outside the school shop I met this guy from holland, his name is Job. After talking for a while about his experiences (wanted to get a feel for the shop) I learned he is working on his open water and really enjoys it. After feeling even more confident of my choice I was starting to get hungry so I asked for recommendations around and ended up hanging out with him for a couple hours at his hostel where I grabbed my first Colombian beer and a so-so baguette. Cool thing was I started talking to these Dutch guys at the hostel and learned of this trek to “Ciudad Perdida” that\'s a 4 day trek south of Tayrona park. Must investigate further. I gave Job my contact info and decided to head back into town... I\'ll be spending more time in Taganga, but I\'m not sure how long I\'ll be around Santa Marta, specially considering my stay with Paloma is until Wednesday.
        (Lunch with Job)
        Another exciting bus ride with many “close calls” and I\'m back in town. Once we’re back to Santa Marta the ride is much more boring without the winding, steep streets up the little mountain between the two towns. To make things worse I decided to go to the opposite side of town and the route goes all over the place so yeah, long and boring. My destination was a museum of sorts my dad recommended. He sent me a message earlier in the morning and I happen to see it as I was getting ready to head out. That\'s how I ended up at La Quinta de San Pedro Alejandrino. I\'m not much of a museum person; I can appreciate art but I\'ve never been that into it, but this was a bit different. This was where Simon Bolivar came to spend his last days alive. For those who don\'t know who he is, we grow up in Venezuela being taught he is basically a hero. He freed most of South America from Spanish rule, founded Bolivia and fought for freedom, democracy and anti-slavery. I mean even Venezuela’s currency is a “Bolivar”... I could go on, but let\'s just say he\'s kind of a big deal. I spend a couple hours there and really enjoyed it. I found it curious that the botanical section of the park was slowly being taken over by nature and last night’s rain basically turned a section into a swamp. Overall a very enjoyable experience and definitely worth checking out though!
        (Fotos del museo)
        Another bus ride and I\'m back in town. This time it was packed and I\'m getting more comfortable yelling to the bus rider to stop at the corner so that\'s a plus. In town I wanted to check out another recommendation I got (this time from Paloma) but the Museum of Gold (museo de oro) closes at 5. Oh well, I ended up buying a very tiny cup of coffee that\'s only 500 COP from this very old  man walking around with a few thermos. I had seen some of the locals sipping on it as they sat and talked and made me want to be cool like them. Walking around the main square and all along the coast with my tiny coffee I started taking in the sights, sounds, conversations and organizing my thoughts a bit. I wandered into a local artisanal shop and asked for food recommendations, I did that a couple more times and after talking to a guy that runs a hostel I finally found a couple places to eat that sounds more “local.” Walked a few more blocks and I arrived at “Restaurante Medellin.” 9k COP ($3) and I had myself a nice meal. Started with a small bowl of soup (with little pieces of chicken bones that I had to be on the lookout for) followed by a plate with rice, lentils, slice of plantain and a cut of beef. Everything was delicious and I walked out very content.

        After the meal I went back, took a shower, watched GoT and wrote this blog. Let\'s try for another early rise tomorrow.',
    :date => DateTime.new(2017, 7, 31)
  },
  {
    :title => 'Santa Marta to Taganga and Scuba',
    :name => 'santa_marta_to_taganga_and_scuba',
    :article => 'Well, I made it in time today! Nice and rested for the day I got all my scuba gear taken care of and off to the boat with my tank. Man, I love scuba diving. The sense of freedom and the thrill of adventure is hard to match. Being in a completely foreign element yet being in control at the same time is a great feeling. Slowly things came back to me. I did a few begging drills to make sure I knew what I was doing (clearing mask under water, losing and recovering regulator, controlling buoyancy, etc) then moved on to slightly more advanced drills. Neat stuff that makes me feel more in control and not just following a guide. Hmm the thought of someday owning my own shop is a tempting one. Anyway, 2 dives, 20-25 meters deep with one short stop to have breakfast and the class was over. Back the next day and depending on water conditions we may wait another day to do the next set of dives. The water was murky and it wasn\'t until around 15 meters that the water started clearing up. We worked on underwater navigation playing and understanding with using a compass underwater and also we worked on advanced buoyancy practicing going up and down and making turns through a structure in an L shape, making sure my body didn\'t hit the edges of it. Sad I didn\'t bring my camera but I will tomorrow. So, again 720 am. Another early start.

      After the scuba diving I met a very friendly girl from South Korea who was doing her Open Water. Her name is Sangeun and we had some very interesting conversations. Later another cool girl from Norway named Victoria met up with us and the hours passed by drinking beer and talking about travels, cultural differences and whatever random things came up. Sangeun and I had lunch and had a pretty decent fish dish with soup as a starting entry for about 15 COP. For dinner the three of us saw an empanada stand while drinking and I had a fish empanada and a papa rellena with sausage inside (2.5k and 2k COP) with a few beers thrown in the mix of course (2.5k COP per beer). So much for it being the last time I had those. Job was there for the scuba since he was finishing up his Open Water but he ended up going to his hostel to finish his homework and didn\'t end up seeing him again unfortunately.

      Fun day filled with both relaxing and adventure. Now I must finish my own homework and pack and get ready for tomorrow, I haven\'t heard from any of the couchsurfers I tried to contact so I\'m taking all my stuff first thing in the morning and getting a hostel in Taganga. Shirly at the scuba shop mentioned I may get a discount for being with them so I will look into that as well. Too bad Paloma has a trip to Bogota tomorrow, I would have loved to hang out more and get to know her better. If you ever come to Colorado come crash my couch!

      If you\'re looking for do any scuba I can\'t recommend Reef Shephard enough. Very friendly, reasonable prices and it\'s obvious they care about scuba diving and people\'s enjoyment of it.',
    :date => DateTime.new(2017, 7, 29)
  },
  {
    :title => 'Taganga and 2nd Scuba Dive',
    :name => 'taganga_and_2nd_scuba_dive',
    :article => 'Woke up early and made my way to Taganga. The day scuba diving was much better! A girl named Ren from Holland met up with us and joined my team for Scuba. Junior has been my instructor and he\'s pretty great. Very amicable and he\'s a local from Santa Marta! Ren did really well and I was happy she joined us. This time we worked on a couple different skills: multi level diving and deep water. We went down to 30m and experienced the effects of oxygen narcosis. Pretty amusing stuff trying to put a puzzle together underwater. I brought my camera so whenever I get some time I will put together a video.

        After the diving I hung out with Ren pretty much all day. So far people from holland have left an outstanding impression. Such friendly and down to earth people. Unfortunately we’re not heading in the same direction but I hope our paths cross again down the road! Best of luck Ren! Day spent relaxing on the beach, going for a swim, playing frisbee and walking around.

        Ended up staying at the hostel recommended by the shop and got a pretty good deal of 25k per night ($8.3) and I also booked for Friday night when I will do the night dive. I could have scuba the next day and gotten my certification done but I\'d rather wait for Friday when they will do a night dive and join for that. It\'s one of the main reasons I decided to do the class and I\'d rather come back and work on that skill than do one of the  other optional ones.

        Anyway, the hostel is called Villa Mary and I highly recommend it. The owner is Italian and his family lives there as well. At night Ren and I fixed up a quick dinner since it was raining hard out and spend the evening talking and playing with some local kids, playing cards with some of the people staying there and watching a movie they had playing on the projector (The Martian).

        Next day the plan will be to either check out Minca or Tayrona park. I took what I think I will need and stuffed my day pack full. They offered to hold on to my backpack and keep it safe so I took them up on that. Hopefully I\'m not forgetting anything!

        Side note: I may be developing an addiction to coffee...',
    :date => DateTime.new(2017, 8, 02)
  },
  {
    :title => 'To Minca',
    :name => 'to_minca',
    :article => 'Woke up at 830 and I was glad to get some rest finally. Turns out that Sengeun was also going to Minca so after a quick breakfast I got my stuff ready, checked out, went down to the shop to turn in my homework and confirm the night dive for Friday. I also said bye to Ren and wished her the best. After all that another Swiss girl  named Tuva joined us and we made our way to the Mercado in Santa Marta where we heard we can take a bus to Minca. 8k COP and we jumped on the van to make our way through the windy roads to Minca.',
    :date => DateTime.new(2017, 8, 03)
  },
  {
    :title => 'Minca, Cerro Kennedy and back to Taganga',
    :name => 'minca_cerro_kennedy_and_back_to_taganga',
    :article => 'Damn this is much harder to write when I don\'t keep up with it daily. Slippery slope!

        So, Minca turned out to be a great choice! It\'s right up my alley with tons of hiking, lush vegetation and tons of things to check out. I went with Tuva and Sengun up the steep hill to the Eden of Minca, the hostel they wanted to stay in. There are motorbikes that will take you there but they were ok with hiking so up we went. After roughly 20 min of hiking we made it. The view is magnificent and I\'m getting more and more excited to keep hiking. I kind of decide that I want to go as high as I can while I\'m here.
        (Motorbike, Eden)
        We grabbed lunch at a local restaurant. We got a plate for 2 that I split with Sengun. Beer, coffee and water and tons of meat, it was about 23k COP each. After lunch we started hiking to Pozo Azul… highly recommend it! The water was rough and murky because of all the rain they\'ve gotten but that didn\'t stop me, I still jumped in only wearing my underwear. The girls stayed out because it was kind of cold, plus I don\'t think they had swimsuits handy. I also wanted to jump off a ledge so after scouting the bottom of the river bed I decided it was safe enough. Bracing myself I jumped and it was great! Did it a few more times just because I could and then we moved on. I went hiking to the end and found a nice place fenced off… but again, that didn\'t stop me. So I kept going and found the best spot in pozo azul. Too bad the girls didn\'t come with so I had to head back soon after lest they leave me behind.
        (Lunch, Pozo Azul, Fence, Hidden Pozo, Selfie)
        At this point we split up, they went back down to their hostel but I wanted to hike up and see how far I get. We made tentative plans to meet up tomorrow around 11 am at a lookout point that\'s part of the loop they\'re planning on doing the next day.
        Off I go on my own and as it turns out it was already 3pm. Where does the time go?! I only have 3 hours of light and Cerro Kennedy is supposed to be 8 hours hiking up from Eden, hmm maybe I should revise my plan, camping doesn\'t seem to be an option since to either side of the road there aren\'t any flat parts, only drop offs or thick vegetation… so wondering if I should hike back to the hostel and cash up the 30k COP for a hammock stay, I run into a sign for Hacienda Victoria, one of the things Ren recommended to me. Well, I thought, since I\'m here anyway might as well check it out. On my way I run into a donkey. He\'s just there, chilling, we have a staring contest for a while and then I just walk by him. Huh.
        (Donkey)
        I get to Victoria right at 5, as they\'re closing and shutting down for the night. Sad I missed the tour I bang on the door and ask them if I can at least buy a cup of coffee, I need fuel! They let me inside and I talk to them while sipping on my coffee, trying to get information and an idea of what to do. They tell me I\'m crazy for hiking this late in the rain (it was only a drizzle and I have rain jacket and pants so I scuff at that comment). They say I should just stay at the hostel nearby and get an early start. Rain can pour at any moment and it will make the climb not only harder, but very dangerous as well. Hmm they are kind of making sense… I thank them for the coffee and go up to the hostel, it\'s a shortcut for the way I was going anyway, the other option being backtracking to the main road by Mr. Donkey. The hike up to the hostel was a pain in the ass! Beautiful but once I got to the top I was panting and very worn out, the day has officially caught up to me. I couldn\'t help being awed by the beauty of the landscape so after finding out it was only 15k COP for a Hammock stay I took it and immediately got a beer (10k COP) from the local brewery (that\'s actually in front of Victoria) and sat overlooking the beautiful land. I talked to a couple people at the hostel but since I had an early start the next day I just set up in my hammock, watched an episode of Better Call Saul and passed out.
        
        I woke up at 530, an hour after what I intended. It still wouldn\'t have been enough time and I would have missed my meet up with the girls anyway… spoiler alert! I start out at 6 and make my way to Cerro Kennedy. I run into dogs, people heading to work, some greeting me, some honking (as a greeting) and some ignoring the crazy tourist... no more donkeys unfortunately. I passed another group of hikers pretty early on and never saw them again, I assume they were doing the loop and not Cerro Kennedy. I use the map I found at the hostel and I find that I\'m faster than how long people say it takes to every checkpoint so I feel great. Around 9 am I realize I\'m not going to make it up and down by 11 and a stab of guilt kicks in, I could have easily done the loop and met them but the peak calls, the hike is fun and I don\'t want to turn away from the challenge. Sorry Sengeun, I hope you don\'t wait long for me. Knowing I\'m not pressed for time I find a local kiosk and ask for some coffee, they don\'t have any but he says the neighbor has some and I just approach a bunch of locals chatting and ask for coffee. Thankfully they don\'t turn me down and sell me a generous cup for 1k COP and I join up their conversation.
        
        Energized and on a mission I start my hike back up. I run into some lookouts, it drizzled at times and I ran into less and less people. Not many head up this way apparently. Once I got to San Lorenzo and the last 2 hours of the hike the fog kicks in. It\'s nice because it keeps me cool and covered from the sun but a thought kicks in, what if it\'s cloudy at the top! Affirming my suspissions the fog only disappeared a couple times and once I got to the top of Cerro Kennedy the view was clouded all over. I find out that at the top there\'s actually a military base and I had a nice conversations with two soldiers who told me it\'s very hard to come for the view since it\'s only clear at the very early hours of the morning. Oh well, I still enjoyed the hike, completed my challenge and actually made it in 6 hours vs the 8 hours people say it took them back at the hostel. After asking the soldier to take a picture of me, I start the decent at 1230. Oh and one of the soldiers was born in Venezuela but raised in Colombia… I guess they\'re called Venecos.
        
        Hiking back it starts to drizzle again, making the decent a bit slower. Once I hit the second antenna, where nearbyis an unmanned hostel, I decide to go into the antenna building and ask for water or food. At this point I already drank all my water and ate what little I brought. My hopes of having lunch were dwarthed by how desolate this trail/road is. The guy stationed gave me water for free and offered to cook me up some lunch. As much as I would have loved to stay and join him I had a scuba session later in the day and I was starting to worry. I can usually decent a hike in half the time it takes me to climb it so I tell myself I have time… I did, however, fail to account for rain! Another hour down and it starts to rain, followed by a downpour. It\'s 230 and I\'m making no progress. My hopes of catching up with
        Sengeun on her loop go out the window, now I\'m worried I won\'t make it to the scuba session. My only hope is to hitchhike. Shortly after a truck rolls by and they took me in! Well, before you think it\'s all good and fun let me spoil the story again and tell you I won\'t be doing any scuba that night…
        The hike up felt very much like I was in the movie Alien vs Predator, I felt like there were creatures camuflaged watching me the whole time. The way down, however, felt very much like Jurassic Park. I kept waiting for T-Rex to bite the roof off the little truck. Meanwhile we’re rocking heavily back and forth while the driver tried to get us safely down. The two guys who gave me a ride are from Santa Marta and they work for the antennas on the mountain, they were doing some routine work on the antenna at the military base at the top and were heading back to Santa Marta… Lucky! The truck had to be one of the earlier versions of a Toyota Land Cruiser and man was I impressed. It handled everything very well and the only thing lacking was comfort. Well, and the body felt like it may just fall apart at any point but 10/10 marks for performance!
        I bought the guys some empanadas in Minca as thanks for the ride and made it to Santa Marta at 530. Now I just have to find a bus and I\'ll be on time! 10 min roll by and nothing… there\'s a lot of traffic… I finally see one and get on. Man this is going slow… where am
        I anyway. Turns out I failed to account for a couple more things that may seem obvious in hindsight. First being rush hour, oh yeah, every city has those huh. Second I was dropped off nowhere near where I usually take the bus. I was on the outskirts and the bus still had to do its whole rout through the city. Long story short, I made it to Taganga at 630, 30 min late and now I\'ll have to reschedule! What a pain, I blame the rain… not any of my miscalculations. I head back to the hostel after apologizing profusely and stayed in all night basically. Bought a small baguette from an old lady who makes bread daily and goes around selling it (2.5k COP), got a beer and some cheese for the bread at the hostel , wolfed it down, took a shower and was on my phone the rest of the night. What a long day… and post… sorry!',
    :date => DateTime.new(2017, 8, 05)
  },
])
